# Generated by Django 3.2.4 on 2021-06-17 13:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateur',
            new_name='profil',
        ),
    ]
