# Generated by Django 3.2.4 on 2021-06-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_utilisateur_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profils'},
        ),
    ]
